### ISSUE TITLE
Movie Matching

### ISSUE THREAD

**Issue by theimmortal68** [Buried-In-Code/Mediux-Posters#12]
The matching for movies does not seem to work as well as the TV Shows does. Essentially, anything that is part of a collection (e.g. Fast and Furious) doesn't match. If it is a single entry in MediUX like 6 Underground or 12 Years a Slave it works as expected. I assume this is partly due to how MediUX handles movie collections and possibly because my sets are made with Kometa instead of Plex. I was hoping you had some ideas on how to overcome this. Let me know if there is anything I can provide or do to help in this endeavor.

**Comment by Buried-In-Code** [comment]
Collections are a constant battle as the whole script runs based off TMDB IDs which plex-api makes available for Movies and Tv-Series. Collections on the other hand don't have TMDB IDs attached, my current solution _(which I haven't documented yet sorry)_ is for the user to add the TMDB ID to the label of the Collection using the format `tmdb-<number>`. Originally I had it doing a name lookup but it wasn't very reliable so had to introduce a manual task. If you can think of a better solution, I'm all ears.

**Comment by theimmortal68** [comment]
Okay, I setup a test library with the Fast and Furious collection along with a few random movies that don't belong to collections but are on MediUX. Running the script matched only the non-collection movies, not even individual movie posters were set for any of the FF movies. Added the label as you mentioned and it worked great. I think Kometa will me add custom labels to my collections, I'll have to play with that tomorrow. Very promising.

**Comment by theimmortal68** [comment]
I played with my Kometa template and was able to get Kometa to add the label tmdb-<number>, which then helps Mediux-Posters find the matches. If you want to add this snippet to your documentation, I attached the Kometa yaml I used to test this.

[tmdb.yml.txt](https://github.com/user-attachments/files/18589944/tmdb.yml.txt)

**Comment by csmith1210** [comment]
FYI for anyone coming to this issue for the above yml, I had to change the `label.sync` entry to `Tmdb-<<key>>` because it was getting capitalized in Plex and then would be removed the next run of Kometa because the labels weren't equal.
```
templates:
  collection:
    default:
      collection_order: release
      minimum_items: 2
      collection_order_<<key>>: <<collection_order>>
    optional:
      - collection_section
    minimum_items: <<minimum_items>>
    tmdb_collection_details: <<value>>
    collection_order: <<collection_order_<<key>>>>
    label.sync: Tmdb-<<key>>

dynamic_collections:
  TMDb Collections:
    type: tmdb_collection
    remove_suffix: Collection
    template: collection
```
