### ISSUE TITLE
Feature Request: Add configurable cache_dir option to settings.toml

### ISSUE THREAD

**Issue by sjabby** [Buried-In-Code/Mediux-Posters#49]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the cache directory defaults to system directories which have limited space and can cause permission issues. This makes it difficult to manage cache data properly, especially on servers or systems with small system partitions.

**Describe the solution you'd like**
I would like a configurable `cache_dir` option in the `settings.toml` file that allows users to specify where cached data should be stored. For example:

```toml
exclude_usernames = []
kometa_integration = false
only_priority_usernames = false
priority_usernames = []
cache_dir = "/path/to/custom/cache/directory"

[jellyfin]
base_url = "http://127.0.0.1:8096"
token = "<Token>"

[mediux]
base_url = "https://api.mediux.pro"
token = "<Token>"

[plex]
base_url = "http://127.0.0.1:32400"
token = "<Token>"
```

This should default to current behavior if not specified, create the directory if it doesn't exist, and validate that it's writable.

**Describe alternatives you've considered**

**Additional context**
This would be particularly useful for server deployments, Docker containers where cache should be stored in mounted volumes, and users with limited space on system partitions. The feature would help organize application data better and avoid potential permission or space issues.
